INSERT INTO autors (nombre) VALUES
    ('Joyce Dunbar'),
    ('Eward Flores Masias'),
    ('Raul Huarote Zegarra'),
    ('Mariela Vallejos'),
    ('Ian Sommerville'),
    ('Juan F. Mateos'),
    ('Peter Hünermann'),
    ('David Squires'),
    ('David McDougall'),
    ('Jose Manuel Ortega Candel'),
    ('Vílchez'),
    ('Alicia Durango'),
    ('Genero'),
    ('Joseph Joyner'),
    ('Robert Martin'),
    ('Richard M Stallman'),
    ('Miguel Jiménez'),
    ('Ramon Venturaroque Hernandez');